# Site wide configuration

title: Loxima
description: "Loxima provides managed bluetooth beacon services to maximise customer engagement."
logo: 120x120.gif
teaser: "beacon_sm.jpg"
locale: en_GB
baseurl: 
url: 

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: simon
  web: 
  email: contact@loxima.com
  twitter: LoximaWeb
  bio: ""
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
